assembled_path: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/input/bacteria_fa/
ref_db: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/input/DIAMOND_databases/uniref90.dmnd
abundance_table: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/code/Pipeline/protein_abundance.pq
ncbi_mapping: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/input/idmapping_selected.tab.gz
reads_path: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/input/Isolate_reads
protein_abundance: /ptmp/pboppert/Pathocom/diamond-postprocess-playground/code/Bacteria_to_UniRef_pipeline/abundance_part