assembled_path:  path/to/assembled/bacterial/fasta/files/
reads_path: path/to/bacterial/reads/fasta/files
ref_db: path/to/DIAMOND/ref/database/uniref90.dmnd
ncbi_mapping: path/to/ncbi_mapping/file/idmapping_selected.tab.gz
protein_abundance: path/to/protein_abundance/file